// Code generated by mockery v2.12.1. DO NOT EDIT.

package views

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// SecretsVerifierMock is an autogenerated mock type for the SecretsVerifier type
type SecretsVerifierMock struct {
	mock.Mock
}

// VerifySecret provides a mock function with given fields: _a0
func (_m *SecretsVerifierMock) VerifySecret(_a0 *gin.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretsVerifierMock creates a new instance of SecretsVerifierMock. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSecretsVerifierMock(t testing.TB) *SecretsVerifierMock {
	mock := &SecretsVerifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
